.travis.yml
README.md
examples/README.md
examples/stream-decoder.go
examples/stream-encoder.go
streaming.go
streaming_test.go

Add fully streaming API, inspired by #9.

Add streaming API

---

appveyor.yml

Submit a new appveyor CI config.

---

reedsolomon.go
reedsolomon_test.go
streaming_test.go

Add checks for data and parity to not exceed 255 shards in total.

---

.gitignore
examples/stream-decoder.go

fix example error

---

reedsolomon.go

Split divided the data into `DataShards` blocks and allocates all parity blocks. The allocation is not necessary if the capacity of the passed slice is large enough to hold some/all parity blocks.
This change adds a check whether the capacity of data is large enough to hold all
data and parity blocks. Split now allocates parity blocks only if necessary.
This is currently a performance problem at [minio's](https://github.com/minio/minio) erasure coding (XL) backend.
Fixes #58

fix unnecessary memory alloc in Split

---

reedsolomon.go

No need to re-create data shards if all data shards is present

Improve quick check for case when dataOnly is true

---

galoisAvx512_amd64_test.go

Tests are timing out. Use shorter tests for -short.

Make AVX512 short tests

---

galois.go
galoisAvx512_amd64.go
galoisAvx512_amd64_test.go
galois_noasm.go
options.go
reedsolomon_test.go

Add commandline arg to disable asm for tests.

Add commandline test args

---

galois_arm64.go
galois_noasm.go
galois_notamd64.go
galois_ppc64le.go

Move non-amd64 code to a separate file and remove references in other files.
Fixes #125

Clean up build tags

---

.travis.yml
galoisAvx512_amd64.go

Add 386 as 32 bit test, arm64 and ppc64le since they have assembly.

Add cross compilation

---

galois_arm64.go
galois_arm64.s

Better performce for arm64:
```
BenchmarkGalois128K-8                    1959.91      4917.60      2.51x
BenchmarkGalois1M-8                      1966.29      4932.74      2.51x
BenchmarkGaloisXor128K-8                 1805.36      4265.49      2.36x
BenchmarkGaloisXor1M-8                   1768.39      3585.06      2.03x
```

Faster arm64 implementation that does not use PMULL instruction

---

.travis.yml

Upgrade CI to Go 1.15

---

inversion_tree.go
options.go
reedsolomon.go
reedsolomon_test.go

There appears to be writes to value receivers.
Add `WithInversionCache(bool)` to disable cache.
Fixes #159

Add WithInversionCache and use pointer methods

---

options.go
reedsolomon.go
reedsolomon_test.go

Hi. Custom matrix is needed, for example, for various LRC implementations

Add custom coding matrix support

---

go.mod
go.sum

Fixes long startup time on Xen VM guests due to buggy cpuid passthrough.

Upgrade cpuid

---

leopard.go
leopard_test.go

Also check if we have enough shards when reconstructing.

Add GF16 Split/Join

---

leopard.go
options.go
reedsolomon.go
reedsolomon_test.go

Decode benchmark

---

_gen/gf16.go
galois_amd64.go
galois_gen_amd64.go
galois_gen_amd64.s

No huge difference on the measurable path.

Unroll ifftDIT4/fftDIT4 branches.

---

galois_amd64.go

Eliminate double branching for creating the mask and sending it.

Simplify function selection

---

galois_amd64.go
galois_arm64.go
galois_noasm.go
leopard.go
leopard8.go
options.go
reedsolomon.go
reedsolomon_test.go

MVP: straight port, with minimal differences to FF16. Passes `go test -tags noasm ./...`.
CC @klauspost @odeke-em @musalbas @liamsi

Implement 8-bit leopard variant

---

leopard8.go

Before/after:
```
BenchmarkDecode1KSingle/4+4-32         	   94654	     12664 ns/op	 646.88 MB/s	    1052 B/op	       2 allocs/op
BenchmarkDecode1KSingle/8+8-32         	   76557	     15750 ns/op	1040.26 MB/s	    1053 B/op	       2 allocs/op
BenchmarkDecode1KSingle/16+16-32       	   51087	     23457 ns/op	1396.93 MB/s	    1058 B/op	       2 allocs/op
BenchmarkDecode1KSingle/32+32-32       	   28098	     42161 ns/op	1554.44 MB/s	    1052 B/op	       2 allocs/op
BenchmarkDecode1KSingle/64+64-32       	   14078	     86196 ns/op	1520.63 MB/s	    1060 B/op	       2 allocs/op
BenchmarkDecode1KSingle/128+128-32     	    6482	    183938 ns/op	1425.18 MB/s	    1053 B/op	       2 allocs/op
BenchmarkDecode1KSingle/4+4-32         	  278660	      4268 ns/op	1919.49 MB/s	    1052 B/op	       2 …
```

Add 8 bit errorfield

---

.github/workflows/go.yml
galois_arm64.go
galois_ppc64le.go
reedsolomon_test.go

Untested.
@elias-orijtech If it is possible for you to test on arm64, that would be great

Add ARM64+PPC64LE leopard 8 assembly.

---

leopard8.go

Fix-up to https://github.com/klauspost/reedsolomon/pull/212

Initialize multiply256LUT8 on arm64

---

reedsolomon.go
reedsolomon_test.go

Fix TotalShards() returning wrong value and add test.

Fix & test total extension

---

go.mod

Retract v1.11.2

---

.github/workflows/go.yml

tests: add golang 1.20

---

galois.go
go.mod
reedsolomon.go
reedsolomon_test.go

Fixes #240 - retract v1.11.6
Add re-entrant tests.

Fix matrix buffer sizes

---

matrix.go

I updated the documentation for the IsSquare method to reflect its correct behavior

doc: update IsSquare doc

---

_gen/gen.go
galois_gen_amd64.s

Remove double load on 64 byte loop init

---

benchmark/main.go

We currently only benchmark "encode" and "reconstruct" operations. (-corrupt 0 will actually corrupt up to M shards).
Introduce another special setting "-corrupt -1", which changes the benchmark to call enc.Verify instead of enc.Reconstruct.

benchmark: Add support to test Verify instead of Reconstruct
