examples/simple-encoder.go

Quick fix to get examples/simple-encoder working -- reference to 'data' should be 'dataShards'

Correct reference to dataShards

---

matrix.go
reedsolomon.go
reedsolomon_test.go

Coverage 74.9% -> 92.9%
I would also consider dropping the Encoder interface and renaming the `reedSolomon` type to `Encoder`. I don't think an interface is very useful if there's only one type that implements it.
btw, this package rocks. Previously we were using longhair + cgo, but this is much more convenient (and as fast or faster). Thank you!

Improve test coverage

---

reedsolomon.go
reedsolomon_test.go

Certain choices of `r.DataShards` and `r.ParityShards` would cause a panic when a slice of a certain length was passed to `Split` For example:
```go
enc, _ = New(6, 1)
enc.Split(make([]byte, 7)) // panic: runtime error: slice bounds out of range
```
The problem is that `Split` wants to create 6 data shards of length 2, but there are only 7 bytes of input. After the first 4 data shards are filled, `Split` runs out of data earlier than expected and panics.
To fix this, I simply applied the zero-padding *before* splitting instead of after. The result is a single straightforward `for` loop; cleaner and bug-free!
This bug was discovered by [go-fuzz](https://github.com/dvyukov/go-fuzz/). Fuzzing has not uncovered any additional bugs.

Fix Split panic

---

examples_test.go
reedsolomon_test.go
streaming_test.go

with E5-2630 v2
before:
```
github.com/klauspost/reedsolomon        17.355s
```
after:
```
github.com/klauspost/reedsolomon        4.503s
```

Tests: backport go1.6 rand.Read for speedup tests

---

reedsolomon.go

I found that the origin implement use so many goroutines (`shardSize / 512`) to encode & decode data 
it may make some effects to performance.
here is my patches & benchmarks for the issue. (hope testing under more enviroments)
`hardware: E5-2630 v2  (Intel x86-64 with ssse3)`
`software: linux, go1.6, GOMAXPROCS=2`
```
Performances                          before          after         change
BenchmarkEncode10x2x10000-2           2884.95 MB/s    2837.93 MB/s  0.98x
BenchmarkEncode100x20x10000-2          593.93 MB/s     577.17 MB/s  0.97x
BenchmarkEncode17x3x1M-2              2903.74 MB/s    5197.99 MB/s  1.80x
BenchmarkEncode10x4x16M-2             1992.13 MB/s    3689.69 MB/s  1.85x
BenchmarkEncode5x2x1M-2               2883.78 MB/s    7506.19 MB/s  2.60x
BenchmarkEncode10x2x1M-2 …
```

Optimized encoding & decoding goroutines number

---

reedsolomon.go
streaming.go

The reasoning behind this is that if we have a data block number
of 10, and parity of 10.  Restricting input such that files of
size < 10Bytes should be errored out doesn't seem like the right
approach.
Most erasure subsystems will have static data and parity blocks,
in such case erroring out is not correct since reedsolomon itself
doesn't provide this limitation (please correct me here if i am
wrong :-)).
So removing the check itself is not a problem since most of the
data after the split would be padded with zeros, which is okay
and should be left as application optimization if they wish to
pack small files in this range.
ErrShortData will be still returned in case if the size of data
is empty, or in case of streaming if the size == 0.

ErrShortData shouldn't be returned for data less than dataShards.

---

matrix.go

To avoid slice growth with append operations.

matrix.go: preallocate slice for String() method

---

README.md
galois_amd64.s

Starting position of the comment is now relaxed to be after either 3, 4, or 5 BYTE sequences and/or followed by an optional back slash.
One remaining issue is that BYTES that are wrapped to the next line (extra indented by asm2plan9s to indicate that this BYTE/these BYTES belong to the previous line) are set back to start at position 4.
This makes it difficult to detect whether it is not any another BYTE sequence (not automatically translated from YASM), so if asmfmt could preserve this it would be great.

Compatible version with asmfmt (save one last issue)

---

.travis.yml

Fixes `imports runtime/trace: unrecognized import path "runtime/trace".

Use gofmt instead of goimports for format teting

---

reedsolomon.go
reedsolomon_test.go

If one or more required data shards are still nil and we can't correctly join
them before a reconstruction, return ErrReconstructRequired.
Fixes #33

Make Join return an error if a reconstruction is required first

---

inversion_tree.go
inversion_tree_test.go
reedsolomon.go
reedsolomon_test.go

Hello,
I worked on a similar erasure coding (albeit slower) Go library which you mention in your README [go-erasure](https://github.com/somethingnew2-0/go-erasure).  One thing that I noticed that was missing from your library was that when reconstructing shards, the inverse matrix is calculated every time.  
There are a finite number of these inverse matrices for each encoding scheme.  In fact, there are M choose N where M is the total number of shards and N is the number of data shards.  For example when there are 4 data shards and 2 parity shards that means there are 6 choose 4 inverse matrices possible or 6!/4!(6-4)! = 6!/(4!2!) = (6*5)/2 = 15 inverse matrices.
To speed up reconstruction, we can cache all those inverse matrices either ahead of time or lazily.  This PR takes the …

Add Inverse Matrix caching in a Thread-Safe Lookup Tree

---

reedsolomon.go
reedsolomon_test.go

The upper limit for the total shard count is the field size. Also, this
matches JavaReedSolomon.

Allow 256 total shards

---

options.go
reedsolomon.go
reedsolomon_test.go

PAR1 is a file format which uses a Reed-Solomon code similar
to the current one, except it uses a different (flawed) coding
matrix.
Add support for it via a WithPAR1Matrix option, so that this code
can be used to encode/decode PAR1 files. Also add the option to
existing tests, and add a test demonstrating the flaw in PAR1's
coding matrix.
Also fix an mistakenly inverted test in testOpts().
Incidentally, PAR1 is obsoleted by PAR2, which uses GF(2^16)
and tries to fix the flaw in the coding matrix; however, PAR2's
coding matrix is still flawed! The real solution is to build the
coding matrix like in this repository.
PAR1 spec:
http://parchive.sourceforge.net/docs/specifications/parity-volume-spec-1.0/article-spec.html
Paper describing the (flawed) Reed-Solomon code used by PAR1: …

Add support for PAR1

---

README.md
reedsolomon.go
reedsolomon_test.go
streaming.go
streaming_test.go

Add ReconstructData interface method to allow reconstruction of any missing data shards (as opposed to always all missing shards).
For read only operations this enhances the performance as no unnecessary effort is spent on calculating parity shards.
Also support for the StreamEncoder is added, so when not asked for any parity shards to be reconstructed, it will invoke ReconstructData() instead of Reconstruct().

Add ReconstructData interface method

---

reedsolomon.go
reedsolomon_test.go

This is a backwards-compatible change that can allow saving memory in some situations.
This changes the interface of Reconstruct and ReconstructData to accept
slices of zero length but sufficient capacity for shards to reconstruct,
and reslices them instead of allocating new memory.

Allow reconstructing into pre-allocated memory.

---

README.md
galois_amd64.s
options.go
reedsolomon.go
reedsolomon_test.go

Older systems (typically without AVX2) are more sensitive to misaligned load+stores.
Add parameter to automatically set the number of goroutines.
```
name                  old time/op    new time/op    delta
Encode10x2x10000-8      18.4µs ± 1%    16.1µs ± 1%  -12.43%    (p=0.000 n=9+9)
Encode100x20x10000-8     692µs ± 1%     608µs ± 1%  -12.10%  (p=0.000 n=10+10)
Encode17x3x1M-8         1.78ms ± 5%    1.49ms ± 1%  -16.63%  (p=0.000 n=10+10)
Encode10x4x16M-8        21.5ms ± 5%    19.6ms ± 4%   -8.74%   (p=0.000 n=10+9)
Encode5x2x1M-8           343µs ± 2%     267µs ± 2%  -22.22%   (p=0.000 n=9+10)
Encode10x2x1M-8          858µs ± 5%     701µs ± 5%  -18.34%  (p=0.000 n=10+10)
Encode10x4x1M-8         1.34ms ± 1%    1.16ms ± 1%  -13.19%    (p=0.000 n=9+9)
Encode50x20x1M-8        30.3ms ± 4% …
```

Split blocks into size divisible by 16, add WithAutoGoroutines

---

.travis.yml
README.md
galoisAvx512_amd64.go
galois_amd64.go
galois_arm64.go
galois_noasm.go
galois_ppc64le.go
reedsolomon.go

* Avoid dst bounds check when using noasm ~30% faster.
* Convert multiply table to a slice whenever used.
* Split on 32 byte boundaries instead of 16 byte.

Optimize pure Go version.

---

reedsolomon.go
reedsolomon_test.go

The following part of code has 2 memory allocation:
```go
if len(data) < (r.Shards * perShard) {
// Pad data to r.Shards*perShard.
padding := make([]byte, (r.Shards*perShard)-len(data))
data = append(data, padding...)
}
```
1. `make([]byte, (r.Shards*perShard)-len(data))`
2. `append` function allocates new slice with `capacity = (len(data) + len(padding) + 1)*2` ( More details https://blog.golang.org/go-slices-usage-and-internals )
The following line of code is fixed the problem:
```go
data = append(data, make([]byte, r.Shards*perShard - len(data))...)
```
Because compiler specially optimize this case: https://github.com/golang/go/issues/21266
Old code benchmark:
```go
BenchmarkSplit10x4x160M-4   	      30	  54329722 ns/op	329253216 B/op	       3 allocs/op
BenchmarkSplit5x2x5M-4 …
```

Split: Reduce memory allocation

---

reedsolomon.go

This commit limits the capacity (additionally
to the length) of each shard to the shard size.
Before this change the following code behaves in
an unexpected way:
```
shards := encoder.Split(buffer)
// ...
shards[0] = shards[0][:cap(shards[0])]
```
Instead of restoring the length of `shards[0]` to
the shard size, it assigns the entire memory of `buffer`
to `shards[0]`.

limit capacity of shards to shard size

---

galois.go

No need to convert to byte here.

Avoid unnecessary conversion

---

streaming.go

creads & cwrites both seem to be unused.

Removed unused struct members

---

options.go
reedsolomon.go

Use L1 cache size to set default split size.
Improves small block performance
```
benchmark                                 old MB/s      new MB/s      speedup
BenchmarkEncode10x2x10000-32              10860.74      19547.78      1.80x
BenchmarkVerify10x2x10000-32              5069.17       10488.04      2.07x
BenchmarkReconstruct10x2x10000-32         14243.36      61903.08      4.35x
BenchmarkReconstructData10x2x10000-32     21304.85      61961.95      2.91x
BenchmarkStreamEncode10x2x1M-32           1478.88       1746.02       1.18x
```

Use CPU to set minSplitSize

---

galois_amd64.go
galois_test.go

40% faster on the pure operation.
```
benchmark                                old ns/op     new ns/op     delta
BenchmarkParallel_8x8x05M-8              2990849       2763554       -7.60%
BenchmarkParallel_8x8x1M-8               4941575       5061619       +2.43%
BenchmarkParallel_8x8x8M-8               34257722      33192541      -3.11%
BenchmarkParallel_8x8x32M-8              143157262     131654688     -8.03%
BenchmarkGalois128K-8                    64201         38374         -40.23%
BenchmarkGalois1M-8                      507053        307236        -39.41%
BenchmarkGaloisXor128K-8                 63815         63157         -1.03%
BenchmarkGaloisXor1M-8                   506369        505641        -0.14%
BenchmarkEncode10x2x10000-8              96414         92781         -3.77% …
```

Remove a bounds check in pure Go

---

options.go
streaming.go

Numbers speak for themselves:
```
benchmark                                old ns/op     new ns/op     delta
BenchmarkStreamEncode10x2x10000-32       4792420       7937          -99.83%
BenchmarkStreamEncode100x20x10000-32     38424066      473285        -98.77%
BenchmarkStreamEncode17x3x1M-32          8195036       1482191       -81.91%
BenchmarkStreamEncode10x4x16M-32         21356715      18051773      -15.47%
BenchmarkStreamEncode5x2x1M-32           3295827       412301        -87.49%
BenchmarkStreamEncode10x2x1M-32          5249011       798828        -84.78%
BenchmarkStreamEncode10x4x1M-32          6392974       904818        -85.85%
BenchmarkStreamEncode50x20x1M-32         29083474      7199282       -75.25%
BenchmarkStreamEncode17x3x16M-32         32451850      28036421 …
```

Fix stream allocations

---

galois_amd64.go
galois_amd64.s
reedsolomon.go

Not super clean benchmark run, but `BenchmarkGalois` is consistently faster.
```
benchmark                                 old ns/op     new ns/op     delta
BenchmarkGalois128K-32                    2551          2261          -11.37%
BenchmarkGalois1M-32                      22492         21107         -6.16%
BenchmarkGaloisXor128K-32                 2972          2808          -5.52%
BenchmarkGaloisXor1M-32                   25181         23951         -4.88%
BenchmarkEncode10x2x10000-32              5081          4722          -7.07%
BenchmarkEncode100x20x10000-32            383800        346655        -9.68%
BenchmarkEncode17x3x1M-32                 264806        263191        -0.61%
BenchmarkEncode10x4x16M-32                8337857       8376910       +0.47%
BenchmarkEncode5x2x1M-32 …
```

avx2: Add 64 bytes per loop processing

---

galois_amd64.go
galois_arm64.go
galois_noasm.go
galois_ppc64le.go
galois_test.go
reedsolomon.go
reedsolomon_test.go

When multiplying by one we can use faster math.
'0' is not used in real life, except on broken stuff.

Do fast by one multiplication

---

galoisAvx512_amd64.go
galoisAvx512_amd64.s
galoisAvx512_amd64_test.go
reedsolomon_test.go

AVX512 version handling (up to) 8 input rows in parallel to generate a single output row.
Can speed up cases with uneven parity significantly as per:
```
$ benchcmp loop.txt parallel81.txt 
benchmark                      old MB/s     new MB/s     speedup
BenchmarkParallel_8x3x1M-4     4445.49      14375.89     3.23x
BenchmarkParallel_8x4x1M-4     19074.16     19610.58     1.03x
BenchmarkParallel_8x5x1M-4     3008.53      11547.82     3.84x
```

Avx512 parallel81

---

reedsolomon_test.go

Always corrupt at least one shard and don't shuffle shards.

bench: Fix reconstruct benchmarks

---

README.md
options.go
reedsolomon.go
reedsolomon_test.go

WithFastOneParityMatrix will switch the matrix to a simple xor if there is only one parity shard.
The PAR1 matrix already has this property so it has little effect there.

Add pure XOR for 1 parity

---

.travis.yml

The s390x seems quite unstable, so we allow failures on it.

Allow s390x failures

---

galois.go
galois_gen_amd64.s
gen.go
reedsolomon.go
reedsolomon_test.go

* Remove 50% of bounds checks when copying.
* Use RIP only addressing, free one register.
```
benchmark                                 old MB/s      new MB/s      speedup
BenchmarkGalois128K-32                    57663.49      58005.87      1.01x
BenchmarkGalois1M-32                      49479.31      49848.29      1.01x
BenchmarkGaloisXor128K-32                 46310.69      46501.88      1.00x
BenchmarkGaloisXor1M-32                   43804.86      43984.39      1.00x
BenchmarkEncode10x2x10000-32              25926.93      27457.75      1.06x
BenchmarkEncode100x20x10000-32            2635.82       2818.95       1.07x
BenchmarkEncode17x3x1M-32                 63215.11      61576.76      0.97x
BenchmarkEncode10x4x16M-32                19551.54      19505.07      1.00x …
```

Faster AVX2 encoding

---

go.mod
go.sum
reedsolomon_test.go

Use total data size (data+parity) as benchmark sizes for more consistent benchmarks.

tests: Set full data size as number of bytes

---

reedsolomon.go
reedsolomon_test.go
streaming_test.go

This fixes #35.
In addition to removing the check for 0 parity shards, I added some short-circuit conditionals to avoid useless work. I also added some tests for the 0 party cases.
I am not highly experienced with Go so any feedback is welcome.

Allow zero parity shards

---

galoisAvx512_amd64.s
galois_amd64.s
galois_arm64.s
galois_ppc64le.s

According to [document of build tags](https://golang.org/cmd/go/#hdr-Build_constraints), `space` equals to OR, `comma` & `newline` equals to AND. So the logic of build tags of gccgo is wrong, causing errors when using gccgo.

Fix build tags for gccgo

---

reedsolomon.go

if `len(data) > (r.Shards * perShard)`, it will use the remaing space of data to padding the last shard, if these value of data is not zero, the padding will is not zero too.
if you have some good ideas, please give me some suggestions, thanks.

fix: avoid the padding of last data shard is not zero

---

README.md
reedsolomon.go
reedsolomon_test.go

Hi, and here is another feature - partial data shard reconstruction. It allows to reconstruct only some data shards, but not all of them. It is relevant for software that does partial reads from a degraded erasure coded data set.

Implement ReconstructSome() to reconstruct only specific data shards

---

reedsolomon_test.go

I suspect it was just a typo/copypaste mistake, am I right?

TestReconstructData was probably meant to call testReconstructData()

---

.github/workflows/go.yml
leopard.go
reedsolomon.go
reedsolomon_test.go
streaming.go

This is a O(n*log n) implementation of Reed-Solomon
codes, ported from the C++ library https://github.com/catid/leopard.
The implementation is based on the paper
"Novel Polynomial Basis with Fast Fourier Transform
and Its Application to Reed-Solomon Erasure Codes"
Several TODOs are left for future commits:
- Performance optimizations, in particular SIMD and multiple goroutines
- Streaming methods
- Merging of reedSolomonFF16 and reedSolomon types
- Turn the straight C++ port into more idiomatic Go
CC  @odeke-em

Add an efficient implementation of shard counts up to 65536

---

leopard.go

* Send `*[65536]ffe` instead of slice, so 16 bit lookups can be done without bounds checks.
* Unroll fwht4
* Move `s2` out of loop.
* Load values instead of modifying pointers.
```
BenchmarkDecode1K/16x16-32                  1029           1175899 ns/op          27.87 MB/s       16410 B/op         17 allocs/op
BenchmarkDecode1K/32x32-32                  1023           1184744 ns/op          55.32 MB/s       32794 B/op         33 allocs/op
BenchmarkDecode1K/64x64-32                   979           1240467 ns/op         105.66 MB/s       65701 B/op         65 allocs/op
BenchmarkDecode1K/128x128-32                 922           1314928 ns/op         199.36 MB/s      131703 B/op        129 allocs/op
BenchmarkDecode1K/256x256-32                 792           1530508 ns/op         342.56 MB/s …
```

Improve fwht speed

---

README.md
leopard.go
reedsolomon_test.go

Use bitfields for progressive reconstruction.
For now only enabled when less than a fourth of parity shards are missing.

Add Leopard bitfield

---

leopard8.go
reedsolomon_test.go

Split large input into 8KB slices for en/decodes for cache locality.
Mainly a benefit for large encodes:
```
BenchmarkEncodeLeopard50x20x1M-32    	      49	  23850959 ns/op	3077.46 MB/s	      24 B/op	       1 allocs/op
BenchmarkEncodeLeopard50x20x1M-32    	     100	  11016534 ns/op	6662.74 MB/s	    1816 B/op	       2 allocs/op
BenchmarkReconstructLeopard50x20x1M-32    	      12	  94149175 ns/op	 779.62 MB/s	11185758 B/op	      13 allocs/op
BenchmarkReconstructLeopard50x20x1M-32    	      39	  34056205 ns/op	2155.27 MB/s	   29109 B/op	       3 allocs/op
```

Split leopard gf8 input

---

galois_amd64.go
galois_amd64.s

Slight speedup on xor heavy loads. Before/after:
```
BenchmarkReconstructLeopard50x20x1M-32    	      38	  33032958 ns/op	2222.03 MB/s	   29820 B/op	       3 allocs/op
BenchmarkReconstructLeopard50x20x1M-32    	      44	  30021986 ns/op	2444.89 MB/s	   26045 B/op	       3 allocs/op
```

Add AVX2 xor

---

leopard8.go

Replace work slices with output slices, so we write directly to output
Saves a memcopy of final result.
Before/after:
```
BenchmarkEncodeLeopard50x20x1M-32                    100          11191776 ns/op        6558.42 MB/s        1816 B/op          2 allocs/op
BenchmarkEncodeLeopard50x20x1M-32                    122           9737593 ns/op        7537.83 MB/s        3352 B/op          3 allocs/op
```

Leopard GF8: Write directly to output

---

galois_amd64.go

GFNI is broken on Leopard GF8 (enabled with `WithLeopardGF(true)`). Disable it until fixed.

Disable broken Leopard GF8 GFNI code

---

streaming.go

Hello author!
OOM occurred when I used stream-encoder for a large file (greater than 10G).
After investigation, I found that the actual memory allocation is used when zero padding in stream.Split() method. 
I think this can be optimized to zero memory used and directly written to the target.
Welcome to correct me, thank you!

zero memery padding on stream split, fix potential OOM issues.

---

galois_amd64.go
go.mod
leopard.go
leopard8.go
reedsolomon.go
reedsolomon_test.go

Fix invalid slicing in #237
Zero values in shards taken from capacity of data shards.
Also fixes GF8 corruption in pure Go mode. Retracting because of this.

Fix split OOB and zeroing

---

leopard.go
leopard8.go
reedsolomon.go

Closes https://github.com/klauspost/reedsolomon/issues/242

Add new error `ErrInvalidShardSize`

---

reedsolomon.go

Speeds up many output EncodeIdx.
Example in #247 twice as fast.
Fixes #247 #245

EncodeIdx: Use advanced AVX2/GFNI

---

leopard.go
leopard8.go
reedsolomon.go
reedsolomon_test.go

Implementation idea for: https://github.com/klauspost/reedsolomon/issues/266

Allow reconstructSome to reconstruct parity shards

---

leopard.go
leopard8.go

When reworking my [Rust implementation of leopard16](https://github.com/AndersTrier/reed-solomon-simd), I realized that the last loop in `fwht` is unreachable.
On the last iteration of the outermost loop, `dist4 == order`, after which we update the value of `dist` to `dist4`, making us unable to enter the body of the last loop.
`order` is always either 256 or 16384, and
```
In [2]: 4<<2<<2<<2
Out[2]: 256
```
```
In [5]: 4<<2<<2<<2<<2<<2<<2
Out[5]: 16384
```
On a related note: [I tried to optimize `fwht` further by using 8 values at a time (`fwht_8`)](https://github.com/AndersTrier/reed-solomon-simd/commit/cc200798ce53fe914fe5f1da92185ec919fce822). It was slightly faster on x86, but slower on ARM.
[`fwht_16`](https://github.com/AndersTrier/reed-solomon-simd/commit/3912577d1878bc4d27d7a39de3 …

Remove dead code in fwht

---

benchmark/main.go

Sample:
```
op	k	m	bsize	blocks	concurrency	codec	processed bytes	duration (μs)	speed (MiB/s)
encode	12	4	10MiB	100	16	vandermonde	258648944000	10039571	24569.45946653347
decode	12	4	10MiB	100	16	vandermonde	251658432000	10014700	23964.788872664616
```

benchmark: Add CSV header

---

galois_arm64.go
galois_arm64.s
go.mod

This is a temp fix for the Graviton4 processor.
(Full fix will be vector-width agnostic as well as take advantage of some further improvements due to support for `SVE2` on Graviton4)

Fix build for Graviton4 processor

---

_gen/gen-arm-sve.go
_gen/gen.go
_gen/go.mod
_gen/go.sum
galois.go
galois_amd64_test.go
galois_arm64.go
galois_arm64_test.go
galois_gen_arm64.s
galois_test.go
options.go
reedsolomon.go

This PR updates the ARM SVE code to be vector length agnostic (so no more "hardcoded" constants but using `addvl` etc. everywhere).
Code has been tested on Graviton 3 with 256-bits vector length (so same vector length as is now supported).
Support for Graviton 4 (128-bits vector length) will be added in a separate PR but should not require any changes to the assembly code itself.

Make ARM SVE code vector length agnostic

---

.github/workflows/go.yml
_gen/gen.go
galois_amd64.go
galois_arm64.go
galois_gen_switch_amd64.go
galois_gen_switch_arm64.go
galois_gen_switch_nopshufb_amd64.go
go.mod
go.sum
race.go
race_none.go
race_none_test.go
race_test.go
reedsolomon_test.go
xor_arm64.go

When calling asm functions in race mode, check inputs and outputs for races.

Test asm slice reads/writes in race tests

---

mulslice.go

As discussed in #293, this PR exports the `galMulSlice` and `galMulSliceXor` functionality. These well-optimized methods are useful in other contexts, including other coding algorithms.

feat: export GalMulSlice and GalMulSliceXor
